/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#2D3E50",
        secondary: "#2C3E50",
        accent: "#3498DB",
        "accent-light": "#85C1E9",
        dark: "#1A202C",
        light: "#F8FAFC",
        "gray-dark": "#4A5568",
        "gray-light": "#EDF2F7",
        "bg-gradient-start": "#D6EAF8",
        "bg-gradient-end": "#FFFFFF",
        "ele-bg": "#FAF8F5",
        "ele-surface": "#FFFFFF",
        "ele-text": "#1A1A1A",
        "ele-text-secondary": "#6B6B6B",
        "ele-text-tertiary": "#9A9A9A",
        "ele-border": "#E8E4DF",
        "ele-joy": "#F59E0B",
        "ele-grief": "#3B82F6",
        "ele-rage": "#EF4444",
        "ele-hope": "#10B981",
        "ele-anxiety": "#F97316",
        "ele-empathy": "#8B5CF6",
        "ele-apathy": "#9CA3AF",
        "ele-outrage": "#DC2626",
        "ele-up": "#059669",
        "ele-down": "#DC2626",
        // Atlas (Aaron West Lyric Atlas)
        "atlas-bg": "#FAF6F0",
        "atlas-text": "#2C2C2C",
        "atlas-text-secondary": "#6B6358",
        "atlas-text-muted": "#9A9189",
        "atlas-border": "#E6DFD6",
        "atlas-steel": "#2D5F8A",
        "atlas-brown": "#8B6E4E",
        "atlas-green": "#4A7C59",
        "atlas-amber": "#D4813B",
        "atlas-purple": "#7B4B6A",
        // Plot Twist (Story Discovery)
        "pt-bg": "#0F0F1A",
        "pt-surface": "#1A1A2E",
        "pt-text": "#F0F0F0",
        "pt-text-secondary": "#A0A0B8",
        "pt-text-muted": "#6B6B80",
        "pt-border": "#2A2A3E",
        "pt-accent": "#8B5CF6",
        "pt-like": "#EF4444",
        "pt-dislike": "#6B7280",
        "pt-scifi": "#06B6D4",
        "pt-fantasy": "#8B5CF6",
        "pt-horror": "#EF4444",
        "pt-literary": "#F59E0B",
        "pt-humor": "#10B981",
        "pt-thriller": "#F97316",
        // Invoice Generator
        "inv-bg": "#FAFAF7",
        "inv-gold": "#C49A3C",
        "inv-text": "#1A1A1A",
        "inv-band": "#F5F5F0",
        "inv-border": "#E8E4DF",
        // Link Light Rail Tracker
        "link-bg": "#F0F4F8",
        "link-text": "#1A2B3C",
        "link-text-secondary": "#4A5D6F",
        "link-text-muted": "#8899AA",
        "link-border": "#D4DDE6",
        // Official Sound Transit line colors
        "link-1line": "#3DAE2B",
        "link-2line": "#00A0DF",
        "link-3line": "#ED40A9",
        "link-4line": "#B14FC5",
        "link-tline": "#F38B00",
        // Monetized Reader (The Happiness Liability excerpt)
        "mr-bg": "#07090D",
        "mr-surface": "#0D1117",
        "mr-panel": "#11161D",
        "mr-border": "#1F2733",
        "mr-text": "#E6EDF3",
        "mr-text-secondary": "#8B98A9",
        "mr-text-muted": "#55606E",
        "mr-accent": "#2DD4BF",
        "mr-money": "#F5C542",
        "mr-grief": "#3B82F6",
        "mr-melancholy": "#64748B",
        "mr-curiosity": "#8B5CF6",
        "mr-happiness": "#F59E0B",
        "mr-warning": "#EF4444",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["Poppins", "sans-serif"],
        serif: ['"DM Serif Display"', "Georgia", "serif"],
        mono: ['"JetBrains Mono"', "monospace"],
        "sans-ele": ['"DM Sans"', "system-ui", "sans-serif"],
        "serif-atlas": ['"Libre Baskerville"', "Georgia", "serif"],
        invoice: ['"IBM Plex Mono"', '"JetBrains Mono"', "monospace"],
      },
      boxShadow: {
        custom: "0 4px 6px rgba(0, 0, 0, 0.1)",
        "custom-lg": "0 10px 15px rgba(0, 0, 0, 0.1)",
        "custom-2xl": "0 25px 50px rgba(0, 0, 0, 0.15)",
        "custom-inner": "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)",
      },
      backgroundImage: {
        "hero-pattern": "url('/pattern.svg')",
      },
      animation: {
        blob: "blob 7s infinite",
        "fade-in": "fade-in 0.8s ease-out forwards",
        "reveal-left":
          "reveal-left 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "reveal-right":
          "reveal-right 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "ticker-scroll": "ticker-scroll 40s linear infinite",
        // Plot Twist mood effects
        "pt-rain": "pt-rain 2s linear infinite",
        "pt-float-up": "pt-float-up 6s ease-in-out infinite",
        "pt-drift": "pt-drift 8s ease-in-out infinite",
        "pt-vignette-pulse": "pt-vignette-pulse 5s ease-in-out infinite",
        "pt-flicker": "pt-flicker 3s steps(4) infinite",
        "pt-scanline": "pt-scanline 8s linear infinite",
        "pt-shimmer": "pt-shimmer 4s ease-in-out infinite",
        "pt-fog": "pt-fog 10s ease-in-out infinite",
        "pt-morph": "pt-morph 12s ease-in-out infinite",
        // Plot Twist celebration & interaction animations
        "pt-like-burst": "pt-like-burst 0.6s ease-out forwards",
        "pt-like-flash": "pt-like-flash 0.3s ease-out forwards",
        "pt-stamp-in": "pt-stamp-in 0.3s ease-out forwards",
        "pt-glitch": "pt-glitch 3s steps(5) infinite",
        "pt-double-tap-heart": "pt-double-tap-heart 1s ease-out forwards",
        // Monetized Reader
        "mr-pulse-warning": "mr-pulse-warning 2s ease-in-out infinite",
      },
      keyframes: {
        "ticker-scroll": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        blob: {
          "0%": {
            transform: "translate(0px, 0px) scale(1)",
          },
          "33%": {
            transform: "translate(30px, -50px) scale(1.1)",
          },
          "66%": {
            transform: "translate(-20px, 20px) scale(0.9)",
          },
          "100%": {
            transform: "translate(0px, 0px) scale(1)",
          },
        },
        "fade-in": {
          from: {
            opacity: "0",
            transform: "translateY(10px)",
          },
          to: {
            opacity: "1",
            transform: "translateY(0)",
          },
        },
        "reveal-left": {
          from: {
            opacity: "0",
            transform: "translateX(-40px)",
          },
          to: {
            opacity: "1",
            transform: "translateX(0)",
          },
        },
        "reveal-right": {
          from: {
            opacity: "0",
            transform: "translateX(40px)",
          },
          to: {
            opacity: "1",
            transform: "translateX(0)",
          },
        },
        // Plot Twist mood keyframes
        "pt-rain": {
          from: { transform: "translateY(-100%)" },
          to: { transform: "translateY(calc(100vh + 100%))" },
        },
        "pt-float-up": {
          "0%": { transform: "translateY(0) translateX(0)", opacity: "0" },
          "10%": { opacity: "1" },
          "90%": { opacity: "1" },
          "100%": { transform: "translateY(-100vh) translateX(var(--sway, 20px))", opacity: "0" },
        },
        "pt-drift": {
          "0%": { transform: "translate(0, 0)", opacity: "0" },
          "20%": { opacity: "1" },
          "80%": { opacity: "1" },
          "100%": { transform: "translate(var(--sway, 30px), -30px)", opacity: "0" },
        },
        "pt-vignette-pulse": {
          "0%, 100%": { opacity: "0.3" },
          "50%": { opacity: "0.6" },
        },
        "pt-flicker": {
          "0%, 100%": { opacity: "0.03" },
          "25%": { opacity: "0.08" },
          "50%": { opacity: "0.02" },
          "75%": { opacity: "0.1" },
        },
        "pt-scanline": {
          from: { backgroundPosition: "0% 0%" },
          to: { backgroundPosition: "100% 100%" },
        },
        "pt-shimmer": {
          "0%": { transform: "translateX(-100%)" },
          "50%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-100%)" },
        },
        "pt-fog": {
          "0%": { backgroundPosition: "0% 0%" },
          "50%": { backgroundPosition: "100% 0%" },
          "100%": { backgroundPosition: "0% 0%" },
        },
        "pt-morph": {
          "0%": { transform: "translate(0, 0) scale(1)" },
          "33%": { transform: "translate(20%, -10%) scale(1.2)" },
          "66%": { transform: "translate(-15%, 15%) scale(0.9)" },
          "100%": { transform: "translate(0, 0) scale(1)" },
        },
        "pt-like-burst": {
          "0%": { transform: "scale(0)", opacity: "0.8" },
          "50%": { transform: "scale(1.5)", opacity: "0.4" },
          "100%": { transform: "scale(2.5)", opacity: "0" },
        },
        "pt-like-flash": {
          "0%": { opacity: "0.15" },
          "100%": { opacity: "0" },
        },
        "pt-stamp-in": {
          "0%": { transform: "scale(3) rotate(-15deg)", opacity: "0" },
          "60%": { transform: "scale(0.95) rotate(-12deg)", opacity: "1" },
          "100%": { transform: "scale(1) rotate(-12deg)", opacity: "1" },
        },
        "pt-glitch": {
          "0%, 100%": { transform: "translate(0)" },
          "20%": { transform: "translate(-2px, 1px)" },
          "40%": { transform: "translate(1px, -1px)" },
          "60%": { transform: "translate(-1px, 2px)" },
          "80%": { transform: "translate(2px, -1px)" },
        },
        "pt-double-tap-heart": {
          "0%": { transform: "scale(0)", opacity: "0" },
          "15%": { transform: "scale(1.3)", opacity: "1" },
          "30%": { transform: "scale(1)", opacity: "1" },
          "80%": { transform: "scale(1)", opacity: "1" },
          "100%": { transform: "scale(1)", opacity: "0" },
        },
        "mr-pulse-warning": {
          "0%, 100%": { borderColor: "rgba(239, 68, 68, 0.4)" },
          "50%": { borderColor: "rgba(239, 68, 68, 1)" },
        },
      },
    },
  },
  plugins: [],
};
