// Runtime view of the baked OSM basemap (src/data/basemap.json, generated by
// scripts/build-link-basemap.mjs at the repo root — data © OpenStreetMap
// contributors, ODbL; the HUD shows attribution whenever this is on screen).
//
// The committed file may be the placeholder stub (workflow not yet run):
// HAS_BASEMAP gates every consumer, and Water.tsx falls back to the
// hand-authored waterData.ts rings so the piece never loses its lakes.

import basemapJson from "../data/basemap.json";
import { PROJECTION } from "./network";

export interface BasemapPolygon {
  ring: [number, number][]; // projected km [x, z]
  holes: [number, number][][];
}

interface RawBasemap {
  meta: {
    placeholder: boolean;
    projection: { originLat: number; originLng: number } | null;
    attribution: string | null;
  };
  water: BasemapPolygon[];
  parks: BasemapPolygon[];
  roads: { major: [number, number][][]; arterial: [number, number][][] };
}

const raw = basemapJson as unknown as RawBasemap;

export const HAS_BASEMAP = !raw.meta.placeholder;

if (
  HAS_BASEMAP &&
  raw.meta.projection &&
  (Math.abs(raw.meta.projection.originLat - PROJECTION.originLat) > 1e-6 ||
    Math.abs(raw.meta.projection.originLng - PROJECTION.originLng) > 1e-6)
) {
  // Both files bake through scripts/*; a mismatch means one is stale.
  console.warn("link-map: basemap.json projection differs from network.json — regenerate both");
}

export const BASEMAP_WATER: BasemapPolygon[] = raw.water ?? [];
export const BASEMAP_PARKS: BasemapPolygon[] = raw.parks ?? [];
export const BASEMAP_ROADS = raw.roads ?? { major: [], arterial: [] };
