// Album metadata
export const ALBUMS = {
  wdheo: {
    id: "wdheo",
    title: "We Don't Have Each Other",
    year: 2014,
    color: "#2D5F8A",
    shortName: "WDHEO",
    coverImage: "/images/atlas/wdheo.jpg",
  },
  bittersweet: {
    id: "bittersweet",
    title: "Bittersweet EP",
    year: 2015,
    color: "#8B6E4E",
    shortName: "Bittersweet",
    coverImage: "/images/atlas/bittersweet.jpg",
  },
  orchard: {
    id: "orchard",
    title: "Orchard Park",
    year: 2019,
    color: "#4A7C59",
    shortName: "Orchard Park",
    coverImage: "/images/atlas/orchard-park.jpg",
  },
  routine: {
    id: "routine",
    title: "Routine Maintenance",
    year: 2019,
    color: "#D4813B",
    shortName: "Routine Maint.",
    coverImage: "/images/atlas/routine-maintenance.jpg",
  },
  lieu: {
    id: "lieu",
    title: "In Lieu of Flowers",
    year: 2024,
    color: "#7B4B6A",
    shortName: "In Lieu of Flowers",
    coverImage: "/images/atlas/in-lieu-of-flowers.jpg",
  },
};

export const ALBUM_ORDER = ["wdheo", "bittersweet", "orchard", "routine", "lieu"];

// Map configuration
export const MAP_CONFIG = {
  center: [39.8283, -98.5795], // geographic center of US
  zoom: 4,
  minZoom: 3,
  maxZoom: 18,
  tileUrl: "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",
  tileAttribution:
    '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
};

// All 41 location entries, ordered by narrativeOrder
export const LOCATIONS = [
  // ── We Don't Have Each Other (2014) ──
  {
    id: "our-apartment-brooklyn",
    narrativeOrder: 1,
    album: "wdheo",
    song: "Our Apartment",
    year: 2014,
    location: "Brooklyn, New York",
    lat: 40.6782,
    lng: -73.9442,
    lyric: "I pictured our apartment in the middle of Brooklyn",
    context:
      "Aaron imagines the life he and Dianne built together — the apartment, the mess on the floor. It's already memory.",
  },
  {
    id: "midtown-manhattan",
    narrativeOrder: 2,
    album: "wdheo",
    song: "Our Apartment",
    year: 2014,
    location: "Midtown Manhattan, New York",
    lat: 40.7549,
    lng: -73.984,
    lyric: "I pictured your office in mid-town Manhattan",
    context:
      "Dianne's office. Aaron pictures her walking in late, makeup straight, smiling. The routines of a marriage about to end.",
  },
  {
    id: "west-babylon",
    narrativeOrder: 3,
    album: "wdheo",
    song: "St. Joe Keeps Us Safe",
    year: 2014,
    location: "West Babylon, Long Island, New York",
    lat: 40.7176,
    lng: -73.3543,
    lyric: "Out to West Babylon. I walked up the driveway, saw my Daddy's old car.",
    context:
      "Aaron takes the LIRR home to his mother's house. His father is already gone. The car still sits in the yard, covered up.",
  },
  {
    id: "astoria-queens",
    narrativeOrder: 3,
    album: "wdheo",
    song: "St. Joe Keeps Us Safe",
    year: 2014,
    location: "Astoria, Queens, New York",
    lat: 40.7723,
    lng: -73.9196,
    lyric: "Walk the cold Brooklyn streets towards Astoria, Queens",
    context:
      "The route to his mother's house. Brooklyn to Queens to Long Island — a pilgrimage home when everything else has collapsed.",
  },
  {
    id: "north-jersey",
    narrativeOrder: 4,
    album: "wdheo",
    song: "Runnin' Scared",
    year: 2014,
    location: "North Jersey",
    lat: 40.8838,
    lng: -74.1527,
    lyric: "A memory of you dancing in a backyard in North Jersey, holding sparklers",
    context:
      "A flashback to happiness — Dianne with sparklers in a backyard, silhouetted by porch lights. Aaron is now freezing in a car somewhere far away.",
  },
  {
    id: "georgia-daylilies",
    narrativeOrder: 5,
    album: "wdheo",
    song: "Runnin' Scared",
    year: 2014,
    location: "Georgia",
    lat: 32.6807,
    lng: -83.6431,
    lyric: "I'm gonna go to Georgia, I'm gonna smile in the sun, I'm gonna pick you some wild day-lilies",
    context:
      "Aaron's desperate promise: he'll go south, find warmth, pick flowers, come back whole. The daylilies become a recurring symbol.",
  },
  {
    id: "truck-stop-south",
    narrativeOrder: 6,
    album: "wdheo",
    song: "Divorce And The American South",
    year: 2014,
    location: "Somewhere in the American South",
    lat: 34.0007,
    lng: -81.0348,
    lyric: "I'm lost at a truck stop somewhere in the South. I don't know where I'm going, but I'm figuring it out.",
    context:
      "Aaron calls Dianne from a phone booth at a truck stop. He admits he fucked up, that when they lost the baby he shut off. She doesn't pick up.",
  },
  {
    id: "thunderbird-inn",
    narrativeOrder: 7,
    album: "wdheo",
    song: "The Thunderbird Inn",
    year: 2014,
    location: "The Thunderbird Inn, off I-95",
    lat: 32.0809,
    lng: -81.0912,
    lyric: "I've been sleeping in a motel off 95. The clerk at the desk is nice — he pours me a coffee.",
    context:
      "Aaron bottoms out in a motel. Drinks his last paycheck. A homeless man tells him God's got a plan. The motel owner gives him a break on rent. He sneaks out at 2 AM.",
  },
  {
    id: "st-marys",
    narrativeOrder: 8,
    album: "wdheo",
    song: "Get Me Out Of Here Alive",
    year: 2014,
    location: "St. Mary's Church",
    lat: 32.0474,
    lng: -81.0953,
    lyric: "I parked on the street out in front of St. Mary's. I watched people leave from the mass in the evening.",
    context:
      "Aaron watches church from outside, windows down, hearing the gospel choir. The stained-glass light doesn't reach him. He's starting to believe God hates him.",
  },
  {
    id: "carolina-coast",
    narrativeOrder: 9,
    album: "wdheo",
    song: "Carolina Coast",
    year: 2014,
    location: "Carolina Coast",
    lat: 33.8361,
    lng: -78.6479,
    lyric: "I woke up to shorebirds. I must be close to the sea.",
    context:
      "The lowest point. Aaron wakes on a beach, thinks about drowning. Finds the dead daylilies in his pocket — the ones he picked for Dianne in Georgia. Plants them seaside. Then sees a rust-stained boat still floating, banged up but alive. Decides not to die.",
  },

  // ── Bittersweet EP (2015) ──
  {
    id: "67-cherry-red-payphone",
    narrativeOrder: 10,
    album: "bittersweet",
    song: "67, Cherry Red",
    year: 2015,
    location: "Payphone (calling north to Mom)",
    lat: 33.5,
    lng: -80.8,
    lyric: "Same fucking payphone, I'm calling north to Mom to ask what year the Mustang is",
    context:
      "Aaron sells his dead father's '67 Cherry Red Mustang. A man named Robert takes the wheel and grins — gets the same look in his eyes Aaron's dad always did. Aaron takes the money for a bus ticket and to pay back The Thunderbird.",
  },
  {
    id: "asheville-bus",
    narrativeOrder: 11,
    album: "bittersweet",
    song: "Goodbye, Carolina Blues",
    year: 2015,
    location: "Asheville, North Carolina",
    lat: 35.5951,
    lng: -82.5515,
    lyric: "Took a midnight bus from Asheville, passed like a ghost through Tennessee",
    context:
      "Aaron finally leaves the South. Midnight bus north, passing through Tennessee and past Blacksburg, heading back to New York.",
  },
  {
    id: "port-authority",
    narrativeOrder: 12,
    album: "bittersweet",
    song: "Goodbye, Carolina Blues",
    year: 2015,
    location: "Port Authority Bus Terminal, Manhattan",
    lat: 40.7568,
    lng: -73.9903,
    lyric: "Good morning Manhattan. Stopped at Port Authority.",
    context:
      "Aaron arrives back in New York. Takes the A to the G. Dollar coffee, two sugars, a drop of cream. Bittersweet.",
  },
  {
    id: "brooklyn-return",
    narrativeOrder: 13,
    album: "bittersweet",
    song: "Goodbye, Carolina Blues",
    year: 2015,
    location: "Brooklyn, New York (Apartment 403)",
    lat: 40.6862,
    lng: -73.9747,
    lyric: "God damn, I missed you Brooklyn. I left my winter coat in Charlotte and I'm cursing at the breeze.",
    context:
      "Aaron returns to the old apartment. Dianne is gone. A college kid named Jesse sublet the place. All new furniture. The only thing she left was the couch. 'Dianne don't live here anymore.'",
  },
  {
    id: "rockaway",
    narrativeOrder: 14,
    album: "bittersweet",
    song: "Green Like The G Train, Green Like Sea Foam",
    year: 2015,
    location: "Rockaway Beach, Queens",
    lat: 40.5834,
    lng: -73.8162,
    lyric: "I rode the A line out to Rockaway. I'm always drawn to the water.",
    context:
      "Aaron rides the A train to the ocean. Watches the skyline over shorebreak. Remembers the Carolina coast that almost killed him. The same ocean, seafoam green. 'On a calendar long enough, New York will be returned to the sea.'",
  },

  // ── Orchard Park Single (2019) ──
  {
    id: "dansville",
    narrativeOrder: 15,
    album: "orchard",
    song: "Orchard Park",
    year: 2019,
    location: "Dansville, New York",
    lat: 42.5609,
    lng: -77.6961,
    lyric: "Switch on the radio at Dansville. I comb the static signal looking for the news.",
    context:
      "Aaron drives upstate at dawn, mom asleep against the window. He finds sports talk radio. All the callers singing the blues. He heard this Sammy kid is supposed to be something special.",
  },
  {
    id: "orchard-park",
    narrativeOrder: 16,
    album: "orchard",
    song: "Orchard Park",
    year: 2019,
    location: "Orchard Park, New York (Highmark Stadium area)",
    lat: 42.7738,
    lng: -78.787,
    lyric: "I spread your ashes in Orchard Park, in the creek beyond the east wall, so I know where you are.",
    context:
      "Aaron scatters his father's ashes near the Buffalo Bills stadium. So that come November, when he's screaming at his TV, his dad is screaming with him from Orchard Park.",
  },

  // ── Routine Maintenance (2019) ──
  {
    id: "asbury-park",
    narrativeOrder: 17,
    album: "routine",
    song: "Lead Paint & Salt Air",
    year: 2019,
    location: "Asbury Park, New Jersey",
    lat: 40.2204,
    lng: -74.0121,
    lyric: "Down in Asbury Park, in a sublet I'm renting. I got a new job where I'm out painting houses.",
    context:
      "Rebuilding. Aaron paints houses, plays sad open mics on the boardwalk where they yell for Springsteen. He smiles for the first time this year. The Paramount sign. Violet light on the Fourth of July.",
  },
  {
    id: "ann-street",
    narrativeOrder: 18,
    album: "routine",
    song: "Just Sign The Papers",
    year: 2019,
    location: "Ann Street (lawyer's office)",
    lat: 40.7107,
    lng: -74.0068,
    lyric: "At a big wooden table in an office off Ann Street, it might as well be the ocean for as far as you feel from me.",
    context:
      "The divorce is finalized. Aaron traces the grain of the table. The lawyers rewrite their history. He watches pools of ink dry blue and swears he saw daylilies bloom from the end of his name.",
  },
  {
    id: "fort-greene",
    narrativeOrder: 18,
    album: "routine",
    song: "Just Sign The Papers",
    year: 2019,
    location: "Fort Greene, Brooklyn",
    lat: 40.6892,
    lng: -73.9744,
    lyric: "Burn the memories. Spread the ashes over Fort Greene.",
    context:
      "The divorce divides everything. The things they built get torn down brick by brick.",
  },
  {
    id: "boston-catherine",
    narrativeOrder: 19,
    album: "routine",
    song: "Bloodied Up In A Bar Fight",
    year: 2019,
    location: "Boston, Massachusetts",
    lat: 42.3601,
    lng: -71.0589,
    lyric: "My sister lives up in Boston now. Has a life with her husband and kid. I try not to fuck with it.",
    context:
      "Aaron gets arrested after defending a friend in a bar fight. He can't call Mom. Can't call Catherine in Boston. He's mastering the art of disappearing in the middle of the night.",
  },
  {
    id: "bethlehem",
    narrativeOrder: 20,
    album: "routine",
    song: "Bury Me Anywhere Else",
    year: 2019,
    location: "Bethlehem, Pennsylvania",
    lat: 40.6259,
    lng: -75.3705,
    lyric: "I'm catching out of Bethlehem, chasing trains like I'm 19 again.",
    context:
      "Aaron hops a freight train. A guy from college gets him a crew change. He's heading west — anywhere but here.",
  },
  {
    id: "chicago",
    narrativeOrder: 21,
    album: "routine",
    song: "Bury Me Anywhere Else",
    year: 2019,
    location: "Chicago, Illinois",
    lat: 41.8781,
    lng: -87.6298,
    lyric: "Took the North Line on an IM from Chicago, cut through the winter wheat.",
    context:
      "Freight train through the Midwest. Frozen breath over Whitefish at dawn.",
  },
  {
    id: "whitefish",
    narrativeOrder: 22,
    album: "routine",
    song: "Bury Me Anywhere Else",
    year: 2019,
    location: "Whitefish, Montana",
    lat: 48.4106,
    lng: -114.3528,
    lyric: "Frozen breath hangs in the dawn out over Whitefish",
    context:
      "The freight train pushes west through Montana. Aaron is half asleep, wrapped in diesel fumes.",
  },
  {
    id: "wenatchee",
    narrativeOrder: 23,
    album: "routine",
    song: "Bury Me Anywhere Else",
    year: 2019,
    location: "Wenatchee, Washington",
    lat: 47.4235,
    lng: -120.3103,
    lyric: "I'll swap out in Wenatchee, I'll ride junk down for the rest of the week.",
    context:
      "Through the Cascades. The sun tells him he's on his goddamn way. 'Bury me anywhere else. I couldn't die in New Jersey.'",
  },
  {
    id: "reseda",
    narrativeOrder: 24,
    album: "routine",
    song: "Rosa & Reseda",
    year: 2019,
    location: "Reseda, Los Angeles, California",
    lat: 34.2011,
    lng: -118.5365,
    lyric: "I came to Reseda for the cheap rent and the distant listless gloom.",
    context:
      "Aaron lands in LA. Answers a Craigslist ad — his roommate Rosa waits tables and becomes his first real friend since Dianne. Her boyfriend teaches him Spanish. They think he can be something if he tries.",
  },
  {
    id: "texas-hillside",
    narrativeOrder: 25,
    album: "routine",
    song: "Wildflower Honey",
    year: 2019,
    location: "Texas (hillside)",
    lat: 30.2672,
    lng: -97.7431,
    lyric: "I passed a hillside in Texas where the cacti all raised up their arms like they've been caught in prayer.",
    context:
      "Aaron is touring now. Drifting to sleep eating wildflower honey in the evening heat. Fireflies. Windows down. Laying low on the side of the road.",
  },
  {
    id: "st-louis",
    narrativeOrder: 26,
    album: "routine",
    song: "Wildflower Honey",
    year: 2019,
    location: "St. Louis, Missouri",
    lat: 38.627,
    lng: -90.1994,
    lyric: "I played a dive in St Louis. My guitar started sounding like shit.",
    context:
      "A dive bar gig in St. Louis. The guitar is falling apart. He'll get it fixed in Nashville.",
  },
  {
    id: "nashville",
    narrativeOrder: 27,
    album: "routine",
    song: "Wildflower Honey",
    year: 2019,
    location: "Nashville, Tennessee",
    lat: 36.1627,
    lng: -86.7816,
    lyric: "Got it fixed up in Nashville. The lady said 'Kid you can't bang on your fret-board like this.'",
    context:
      "Guitar repair in Nashville. Then he finds some boys out of Philly willing to play in his band for drinks and the promise of places they've never been.",
  },
  {
    id: "dakota",
    narrativeOrder: 28,
    album: "routine",
    song: "God & The Billboards",
    year: 2019,
    location: "North or South Dakota",
    lat: 46.8772,
    lng: -96.7898,
    lyric: "November out in Dakota, all the unending cold. I watch exhaust from the tail pipes start to blacken the snow.",
    context:
      "On tour in Dakota when the phone rings. Catherine's husband is sick. 'Of course I'm coming home.'",
  },
  {
    id: "long-island-home",
    narrativeOrder: 29,
    album: "routine",
    song: "Routine Maintenance",
    year: 2019,
    location: "West Babylon / Long Island (family home)",
    lat: 40.7176,
    lng: -73.3543,
    lyric: "All of us here under the same roof again. I'm sleeping in Catherine's room in a twin sized bed.",
    context:
      "Aaron comes home. Changes Mom's oil. Rakes leaves. Shovels snow. Brings Colin to school. Tries to be someone you can count on for a change.",
  },

  // ── In Lieu Of Flowers (2024) ──
  {
    id: "cheyenne",
    narrativeOrder: 30,
    album: "lieu",
    song: "Roman Candles",
    year: 2024,
    location: "I-80 West, outside Cheyenne, Wyoming",
    lat: 41.14,
    lng: -104.8202,
    lyric: "I'm picturing us, I-80 West outside Cheyenne, in a rusted 15 passenger trying to guess how far the storm is.",
    context:
      "Aaron's back with the band, counting seconds between thunder and lightning like they did as kids. But his mom works at the hospital and every shift feels like a curse. It's only getting worse. (COVID.)",
  },
  {
    id: "south-shore-garage-doors",
    narrativeOrder: 31,
    album: "lieu",
    song: "Paying Bills At The End Of The World",
    year: 2024,
    location: "South Shore, Long Island",
    lat: 40.6501,
    lng: -73.5479,
    lyric: "Now I install garage doors on the south shore while it lasts.",
    context:
      "COVID era. Aaron's back on Long Island, installing garage doors, no health insurance, walking with Colin after dinner splitting a Coke. This is where he reconnects with Sam.",
  },
  {
    id: "monongahela-park",
    narrativeOrder: 32,
    album: "lieu",
    song: "Monongahela Park",
    year: 2024,
    location: "Monongahela Park, Pittsburgh",
    lat: 40.4328,
    lng: -79.9806,
    lyric: "I rode a freight train out to come visit you at Pitt. And you laugh so loud. Let your hand rest on my knee.",
    context:
      "Aaron visits Sam in Pittsburgh. Cheap scotch as the sky goes dark. She asks if it's hard to still sing about Dianne. He says it's not really up to him. She leans in. He turns his face away. 'My heart's a nail bomb.'",
  },
  {
    id: "london",
    narrativeOrder: 33,
    album: "lieu",
    song: "Alone At St. Luke's / Monongahela Park",
    year: 2024,
    location: "London, England",
    lat: 51.5074,
    lng: -0.1278,
    lyric: "The graffiti on the wall says 'Fuck the Tories.' Outside a takeaway, we're eating on the street.",
    context:
      "The band makes it to the UK. Spitting curses, hopping fences, burning out like true romantics. Shoplifting candy and wine. Mouse shit on the motor lodge carpet. Then everyone gets sick. Aaron is the only one it spared.",
  },
  {
    id: "glasgow",
    narrativeOrder: 34,
    album: "lieu",
    song: "Alone At St. Luke's",
    year: 2024,
    location: "Glasgow, Scotland (St. Luke's Church)",
    lat: 55.8544,
    lng: -4.2351,
    lyric: "The gig's in an abandoned church in Glasgow. The irony's a little on the nose.",
    context:
      "Aaron plays solo in an abandoned church. Cold, wet, lonesome. Stained glass light punches him in the chest. 'As long as we're still here, we might as well keep drinking.'",
  },
  {
    id: "la-collapse",
    narrativeOrder: 35,
    album: "lieu",
    song: "Spitting In The Wind",
    year: 2024,
    location: "Los Angeles, California",
    lat: 34.0522,
    lng: -118.2437,
    lyric: "It never rained in LA the whole year that I lived here. But all day today, it's pissing down a steady rain.",
    context:
      "The collapse. Aaron's hand cramps during Grapefruit. He curses out the label. The band is pissed. Rosa leaves. He blows out his voice. 'I'll see you in the water.'",
  },
  {
    id: "john-wayne-airport",
    narrativeOrder: 36,
    album: "lieu",
    song: "I'm An Albatross",
    year: 2024,
    location: "John Wayne Airport, Orange County, California",
    lat: 33.6757,
    lng: -117.8681,
    lyric: "I bought a flight home out of John Wayne. Could you please come get me?",
    context:
      "Catherine calls. 'I won't let it happen twice. It's time to get up and fix your mess.' Aaron flies home. Southern State Parkway. Colin won't look his way. He's sneaking Jim Beam from bottles stolen off the airplane.",
  },
  {
    id: "southern-state-parkway",
    narrativeOrder: 37,
    album: "lieu",
    song: "I'm An Albatross",
    year: 2024,
    location: "Southern State Parkway, Long Island",
    lat: 40.6951,
    lng: -73.4218,
    lyric: "Southern State Parkway, no one talks the whole ride home.",
    context:
      "The silent drive home from the airport. Colin won't look at him. Aaron's thoughts drift to the Jim Beam hidden in his coat.",
  },
  {
    id: "rehab",
    narrativeOrder: 38,
    album: "lieu",
    song: "Runnin' Out Of Excuses",
    year: 2024,
    location: "Rehab facility, Long Island",
    lat: 40.7282,
    lng: -73.2526,
    lyric: "I checked in on a Sunday. They took my sneakers and my phone.",
    context:
      "Rehab. Aaron's roommate Bobby says hold out for a smoke break. He writes letters to his father. He tries to let go of the pain. He tells the shadow on the wall what a cosmic fucking miracle it is to exist at all.",
  },
  {
    id: "sam-driveway",
    narrativeOrder: 39,
    album: "lieu",
    song: "In Lieu Of Flowers",
    year: 2024,
    location: "Sam's house (Long Island)",
    lat: 40.708,
    lng: -73.304,
    lyric: "Rain on the roof of your parked car. Sam. I was fucking afraid.",
    context:
      "Aaron shows up at Sam's driveway, spills his guts. She says 'Hold on. The wound is gonna mend. In lieu of flowers, shake the dirt off. I'm with you til the bitter end.'",
  },
  {
    id: "greenwich-village",
    narrativeOrder: 40,
    album: "lieu",
    song: "In Lieu Of Flowers",
    year: 2024,
    location: "Greenwich Village, Manhattan",
    lat: 40.7336,
    lng: -74.0027,
    lyric: "I called a club in the village. Booked us a three night stick.",
    context:
      "The band reassembles. Eric flies out. Aaron books a club in the Village. The rebuild begins — again.",
  },
  {
    id: "father-demo-square",
    narrativeOrder: 41,
    album: "lieu",
    song: "Dead Leaves",
    year: 2024,
    location: "Father Demo Square, West Village, Manhattan",
    lat: 40.7324,
    lng: -74.002,
    lyric: "I ride the B down 4th Street, climbed into autumn up MTA stairs, and cut close past the fountain here at Father Demo Square.",
    context:
      "The final scene. Aaron takes a train to the city. Passes through Brooklyn, goes underwater through the tunnel, surfaces in the Village. At Father Demo Square, in November light, he sees Dianne. She's pushing a stroller. She found what she needs. He sees their name on the marquee. He opens the door and walks in.",
  },
];
